// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetCurrentTimes():Promise<main.Data>;

export function SelectClock(arg1:string):Promise<void>;

export function SelectCountdown(arg1:number):Promise<void>;
