// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCurrentTimes() {
  return window['go']['main']['App']['GetCurrentTimes']();
}

export function SelectClock(arg1) {
  return window['go']['main']['App']['SelectClock'](arg1);
}

export function SelectCountdown(arg1) {
  return window['go']['main']['App']['SelectCountdown'](arg1);
}
